name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '🧰 Other'
    label: 'other'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    title:
      - '/\[docs.*\].+/'
  - label: 'bug'
    title:
      - '/\[fix.*\].+/'
  - label: 'feature'
    title:
      - '/\[feat.*\].+/'
      - '/\[feat\]\shelloworld/'
  - label: 'other'
    branch:
      - '/release_.+/'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
no-changes-template: |
  ## No Change
  Free time
references:
  - release.+
